- name: Prepare DB hosts
  hosts: psql_fw
  remote_user: root
  tasks:
    - name: show facts
      ansible.builtin.debug:
        var: ansible_facts
    - import_role:
        name: postgresql
    - import_role:
        name: firefly-iii-db