- name: Prepare DB hosts
  hosts: psql_fw
  remote_user: root
  tasks:
    - import_role:
        name: volume-mount
    - import_role:
        name: postgresql
    - import_role:
        name: firefly-iii-db
