name: 'Spin up infrastructure via Terragrunt'
on:
  workflow_dispatch:
    inputs:
      terragruntAction:
        description: 'Action to take when invoking Terragrunt'
        required: true
        default: 'apply'
jobs:
  terragrunt-plan:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: 'google-github-actions/auth@v1'
        id: 'auth'
        with:
          workload_identity_provider: 'projects/820161525709/locations/global/workloadIdentityPools/selfhoster-gh-v2/providers/selfhoster-gh-prvdr-v2'
          service_account: 'tf-state@ln-gcp-sh-infra-prod.iam.gserviceaccount.com'
          access_token_lifetime: 600s
      - uses: actions/setup-go@v4
        with:
          go-version-file: "./ci/go.mod"
          cache-dependency-path: "./ci/go.sum"
      - name: Install dependencies
        run: go get .
        working-directory: "./ci"
      - name: Build CI binary
        run: go build -o dagger-ci
        working-directory: "./ci"
      - name: Run CI job
        run: ./ci/dagger-ci "${{ github.event.inputs.terragruntAction }}"
