name: 'Spin up infrastructure via Terragrunt'
on:
  - workflow_dispatch
jobs:
  terragrunt-plan:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"
      - uses: 'google-github-actions/auth@v1'
        id: 'auth'
        with:
          workload_identity_provider: 'projects/820161525709/locations/global/workloadIdentityPools/selfhoster-gh/providers/selfhoster-gh-prvdr'
          service_account: 'tf-state@ln-gcp-sh-infra-prod.iam.gserviceaccount.com'
      - name: Run Dagger.io pipeline
        run: go run ci/main.go
