- name: Create dir for volumes
  ansible.builtin.file:
    path: "{{ volumes_mount_dir }}/postgres_data_volume"
    state: directory
    mode: 0755

- name: Mount by label
  ansible.posix.mount:
    path: "{{ volumes_mount_dir }}/postgres_data_volume"
    src: "LABEL={{ volume_fslabel }}"
    fstype: ext4
    state: mounted
    opts: defaults,nofail,discard,noatime
